name: we_are_friends_app
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls

  intl: ^0.17.0
  flutter_svg: ^1.0.3
  simple_shadow: ^0.3.0
  flutter_slidable: ^1.2.0
  slidable_button: ^1.3.1
  flutter_fadein: ^2.0.0
  jiffy: ^5.0.0
  hive:  ^2.2.3
  image_picker: ^0.8.5+3
  image_picker_windows: ^0.1.0+2
  file_selector:  ^0.8.2+1
  file_selector_windows:  ^0.8.2
  image_picker_for_web: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
